-- MySQL Script generated by MySQL Workbench
-- 04/22/17 21:05:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema adsmarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adsmarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adsmarket` DEFAULT CHARACTER SET utf8 ;
USE `adsmarket` ;

-- -----------------------------------------------------
-- Table `adsmarket`.`ads_vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_vendor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `descrption` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adsmarket`.`ads_offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_offer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `original_price` VARCHAR(45) NULL,
  `original_currency` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  `platform` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `cap` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `start_time` VARCHAR(45) NULL,
  `end_time` VARCHAR(45) NULL,
  `requirement` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `vendor_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adsmarket`.`ads_distributor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_distributor` (
  `id` INT NOT NULL,
  `vendor_id` VARCHAR(45) NULL,
  `user_account` VARCHAR(45) NULL,
  `tracking_url` VARCHAR(45) NULL,
  `additional_url` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adsmarket`.`ads_promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_promotion` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `banner_ad` VARCHAR(45) NULL,
  `start_time` VARCHAR(45) NULL,
  `end_time` VARCHAR(45) NULL,
  `fixed_amount` VARCHAR(45) NULL,
  `rate_amount` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `vendor_id` VARCHAR(45) NULL,
  `offer_id` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adsmarket`.`ads_user_offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_user_offer` (
  `id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `offer_id` VARCHAR(45) NULL,
  `tracking_url` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adsmarket`.`ads_cpi_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_cpi_transaction` (
  `offer_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `distributor_id` VARCHAR(45) NULL,
  `device_id` VARCHAR(45) NULL,
  `device_name` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `earning` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  `transaction_id` VARCHAR(45) NULL,
  `timestamp` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  PRIMARY KEY (`offer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adsmarket`.`ads_cpi_click`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_cpi_click` (
  `offer_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `distributor_id` VARCHAR(45) NULL,
  `device_id` VARCHAR(45) NULL,
  `device_name` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `timestamp` VARCHAR(45) NULL,
  PRIMARY KEY (`offer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adsmarket`.`ads_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adsmarket`.`ads_user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fullname` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `account_type` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `phone_1` VARCHAR(45) NULL,
  `identity_id` VARCHAR(45) NULL,
  `date_of_issue` VARCHAR(45) NULL,
  `place_of_issue` VARCHAR(45) NULL,
  `bank_name` VARCHAR(45) NULL,
  `bank_address` VARCHAR(45) NULL,
  `bank_account_name` VARCHAR(45) NULL,
  `bank_account_number` VARCHAR(45) NULL,
  `referee_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
